### ISSUE TITLE
do you want test at rtx 30 or rtx a2000

### ISSUE THREAD

**Issue by grandfatheryun** [suppai/nvidia-overclock#2]

**Comment by Maeiky** [comment]
I tested on A4000 & RTX 2080, both have GDDR6 (Micro for 2080/ Samsung for A4000)
It work, but requires some minor modifications.
The returning mem multiplier seams not to be good for id 14 (GDDR6), "get_memfreq_multiplier" must return 1 instead of 4

In addition, A4000 requires overclocking around +1600, so you will need to change the limitation of the safe range oc
